In [1]:
import numpy as np

-------------------
####Aluno: Tayco Murilo Santos Rodrigues
####Atividade 1: Numpy tutorial
-------------------

#NumPy Array

In [13]:
#How to create an empty and a full NumPy array?

empty = np.empty(3)
print('Array vazio preenchido com lixo na memória:', empty)
full_10 = np.full(3,10)
print('Array preenchido com 10 em todas as posições:',full_10)

Array vazio preenchido com lixo na memória: [0.75 0.75 0.  ]
Array preenchido com 10 em todas as posições: [10 10 10]


In [14]:
#Create a Numpy array filled with all zeros

zeros = np.zeros(3)
print('Array preenchido com zeros em todas a posições:', zeros)

Array preenchido com zeros em todas a posições: [0. 0. 0.]


In [15]:
#Create a Numpy array filled with all ones

ones = np.ones(3)
print('Array preenchido com uns em todas a posições:', ones)

Array preenchido com uns em todas a posições: [1. 1. 1.]


In [18]:
#Check whether a Numpy array contains a specified row

array = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9],[10, 11, 11]])
row = [1,2,3]
print('A linha existe?',row in array.tolist())

A linha existe? True


In [24]:
#How to Remove rows in Numpy array that contains non-numeric values?

array = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9],[np.nan, np.nan, np.nan]])
print(array[~np.isnan(array).any(axis=1)])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [34]:
#Remove single-dimensional entries from the shape of an array

array = np.array([[[1],[2]],[[3],[4]]])
print(array.shape)

print(np.squeeze(array))
print(np.squeeze(array).shape)

(2, 2, 1)
[[1 2]
 [3 4]]
(2, 2)


In [69]:
#Find the number of occurrences of a sequence in a NumPy array

array = [[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]]
print(repr(array).count("9, 4"))

4


In [70]:
#Find the most frequent value in a NumPy array

array = np.array([1,2,3,4,5,6,7,8,9,10,1])
print(np.bincount(array).argmax())

1


In [75]:
#Combining a one and a two-dimensional NumPy Array

array_1d = np.array([1,2,3])
array_2d = np.array([[4,5,6],[7,8,9]])

result = np.vstack((array_1d, array_2d))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
#How to build an array of all combinations of two NumPy arrays?

array1 = np.array([0,1,2,3,4])
array2 = np.array([5,6,7,8,9])

comb = np.array(np.meshgrid(array1,array2)).T
print(comb)

[[[0 5]
  [0 6]
  [0 7]
  [0 8]
  [0 9]]

 [[1 5]
  [1 6]
  [1 7]
  [1 8]
  [1 9]]

 [[2 5]
  [2 6]
  [2 7]
  [2 8]
  [2 9]]

 [[3 5]
  [3 6]
  [3 7]
  [3 8]
  [3 9]]

 [[4 5]
  [4 6]
  [4 7]
  [4 8]
  [4 9]]]


In [83]:
#How to add a border around a NumPy array?

array = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(np.pad(array, 1))

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [86]:
#How to compare two NumPy arrays?

array1 = np.array([0,1,2,3,4])
array2 = np.array([5,6,7,8,9])

print(np.array_equal(array1,array2))

False


In [87]:
#How to check whether specified values are present in NumPy array?

array = np.array([0,1,2,3,4])
print(0 in array)
print(5 in array)

True
False


In [93]:
# How to get all 2D diagonals of a 3D NumPy array?

array = np.arange(27).reshape(3,3,3)
diag = np.diagonal(array,axis1=1,axis2=2)

print(array)
print(diag)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]


In [98]:
#Flatten a Matrix in Python using NumPy

array = np.matrix([[1,2],[3,4]])
flatten = array.flatten()
print(flatten)

[[1 2 3 4]]


In [99]:
#Flatten a 2d numpy array into 1d array

array = np.array([[1,2],[3,4]])
flatten = array.flatten()
print(flatten)

[1 2 3 4]


In [120]:
#Move axes of an array to new positions

array = np.array([[1,2,3]])
print(np.swapaxes(array,0,1))

[[1]
 [2]
 [3]]


In [124]:
#NumPy – Fibonacci Series using Binet Formula

array = np.arange(0,10,1)
length = len(array)
r5 = np.sqrt(5)
alpha = (1+r5)/2
beta = (1-r5)/2
Fibn =  np.rint(((alpha**array)-(beta**array))/r5)
print(Fibn)

[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]


In [126]:
#Counts the number of non-zero values in the array

array = np.array([0,1,2,3,4,0,6,7,8,0])
print(np.count_nonzero(array))

7


In [139]:
#Count the number of elements along a given axis

array = np.array([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print('Numero de elementos na primeira linha:',np.size(array[3]))

Numero de elementos na primeira linha: 4


In [135]:
#Trim the leading and/or trailing zeros from a 1-D array

array = np.array([0,0,0,1,2,3,4,0,0,0])
print(np.trim_zeros(array))

[1 2 3 4]


In [141]:
#Change data type of given numpy array

array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
print(array.astype(int))

[1 2 3 4 5 6]


In [145]:
#Reverse a numpy array

array = np.array([1, 2, 3, 4, 5, 6])
print(np.flip(array))

[6 5 4 3 2 1]


In [154]:
#How to make a NumPy array read-only?

array = np.array([1, 2, 3, 4, 5, 6])
array.setflags(write=False)

print(array[2])
array[2] = 4

3


ValueError: ignored