In [22]:
import numpy as np
import random

In [4]:
#Create a Numpy array with random values

array = np.random.rand(1,5)
print(array)

[[0.41848849 0.08663258 0.03241993 0.43064434 0.42472505]]


In [12]:
#How to choose elements from the list with different probability using NumPy?

numbers = [1,2,3,4,5,6,7,8,9]
choice = np.random.choice(numbers)
print(choice)

2


In [23]:
#How to get weighted random choice in Python

numbers = [1,2,3,4,5,6,7,8,9]
randomlist = random.choices(numbers,(1, 1, 5, 4, 5, 5, 8, 2, 1),k = 3)
print(randomlist)

[3, 5, 7]


In [25]:
#Generate Random Numbers From The Uniform Distribution using NumPy

print(np.random.uniform(size = 5))

[0.08544412 0.61132535 0.18560656 0.98995734 0.6185507 ]


In [38]:
#Get Random Elements form geometric distribution

print(np.random.geometric(0.5, 10))

[1 3 6 1 2 5 1 6 1 2]


In [44]:
#Get Random elements from Laplace distribution

print(np.random.laplace(0.5,10,5))

[ 0.73070603  0.82295882 -2.67638852  5.39898757 -7.18866151]


In [46]:
#Return a Matrix of random values from a uniform distribution

matrix = np.matrix(np.random.uniform(size=(3,3)))
print(matrix)

[[0.29571212 0.25167217 0.39968833]
 [0.74378024 0.11909516 0.62341654]
 [0.01596375 0.70034551 0.65196361]]


In [47]:
#Return a Matrix of random values from a Gaussian distribution

matrix = np.random.normal(size=(3,3))
print(matrix)

[[ 0.45101183 -0.84029206  0.53412666]
 [-0.34387506  0.10893829 -1.74032848]
 [ 0.12934718 -0.51592892  0.16789844]]
