In [25]:
import numpy as np

In [26]:
#How to get the indices of the sorted array using NumPy in Python?

array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
index = np.argsort(array)
print(index)

[9 0 5 1 6 2 7 3 8 4]


In [27]:
#Finding the k smallest values of a NumPy array

array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
k = 5
print(np.sort(array)[:k])

[0 1 2 3 4]


In [28]:
#How to get the n-largest values of an array using NumPy?

array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
k = 5
print(np.sort(array)[k:])

[5 6 7 8 9]


In [29]:
#Sort the values in a matrix

matrix = np.array([[1,3,5],[7,9,2],[4,6,8]])
matrix.sort()

print(matrix)

[[1 3 5]
 [2 7 9]
 [4 6 8]]


In [30]:
#Filter out integers from float numpy array

array = np.array([1, 1.1, 1.2, 2, 3])
result = array[array != array.astype(int)]
print(result)

[1.1 1.2]


In [31]:
#Find the indices into a sorted array

array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
index = np.argsort(array)
print(index)

[9 0 5 1 6 2 7 3 8 4]
