In [48]:
import numpy as np
import random

In [49]:
#Create a Numpy array with random values

array = np.random.rand(1,5)
print(array)

[[0.40552623 0.11067192 0.18015291 0.66283185 0.55539689]]


In [50]:
#How to choose elements from the list with different probability using NumPy?

numbers = [1,2,3,4,5,6,7,8,9]
choice = np.random.choice(numbers)
print(choice)

5


In [51]:
#How to get weighted random choice in Python

numbers = [1,2,3,4,5,6,7,8,9]
randomlist = random.choices(numbers,(1, 1, 5, 4, 5, 5, 8, 2, 1),k = 3)
print(randomlist)

[1, 6, 5]


In [52]:
#Generate Random Numbers From The Uniform Distribution using NumPy

print(np.random.uniform(size = 5))

[0.85393056 0.22133474 0.97266006 0.6762673  0.99443292]


In [53]:
#Get Random Elements form geometric distribution

print(np.random.geometric(0.5, 10))

[1 2 1 1 2 2 1 2 4 2]


In [54]:
#Get Random elements from Laplace distribution

print(np.random.laplace(0.5,10,5))

[-4.6632012   9.21853576 -7.24796459  5.04482175 -3.00660931]


In [55]:
#Return a Matrix of random values from a uniform distribution

matrix = np.matrix(np.random.uniform(size=(3,3)))
print(matrix)

[[0.15043445 0.14493686 0.27048649]
 [0.29880207 0.9879139  0.50216275]
 [0.77792523 0.7868318  0.32641036]]


In [56]:
#Return a Matrix of random values from a Gaussian distribution

matrix = np.random.normal(size=(3,3))
print(matrix)

[[ 0.40161008  0.22862179  0.28928064]
 [-1.99323949  0.0648166  -2.13225051]
 [ 0.59553997 -0.52892482 -0.92797083]]
