In [4]:
import numpy as np

In [7]:
#How to get element-wise true division of an array using Numpy?

array = np.array([1,2,3,4,5])
print(np.true_divide(array, 4))

[0.25 0.5  0.75 1.   1.25]


In [8]:
#How to calculate the element-wise absolute value of NumPy array?

array = np.array([-1, -2, -3])
print(np.absolute(array))

[1 2 3]


In [9]:
#Compute the negative of the NumPy array

array = np.array([1,2,3,4,5])
print(np.negative(array))

[-1 -2 -3 -4 -5]


In [12]:
#Multiply 2d numpy array corresponding to 1d array

array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([1, 2, 3])

print((array1 * array2).T)

[[ 1  4  7]
 [ 4 10 16]
 [ 9 18 27]]


In [13]:
#Computes the inner product of two arrays

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(np.inner(array1,array2))

32


In [16]:
#Compute the nth percentile of the NumPy array

array = np.array([1,2,3,4,5])
nth = 10
print(np.percentile(array,nth))

1.4


In [24]:
#Calculate the n-th order discrete difference along the given axis

array = np.array([1,2,3,4,5])
nth = 1
print(np.diff(array, nth))

[1 1 1 1]


In [26]:
#Calculate the sum of all columns in a 2D NumPy array

array = np.array([[1,2],[3,4]])
print(np.sum(array, 0))

[4 6]


In [28]:
#Calculate average values of two given NumPy arrays

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print((array1 + array2) / 2)

[2.5 3.5 4.5]


In [30]:
#How to compute numerical negative value for all elements in a given NumPy array?

array = np.array([1,2,3,4,5,6,7,8,9])
print(np.negative(array))

[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [33]:
#How to get the floor, ceiling and truncated values of the elements of a numpy array?

array = np.array([2.45, 3.65, 4.98])

print('Floor:', np.floor(array))
print('Ceiling:', np.ceil(array))
print('Trucated:',np.trunc(array))

Floor: [2. 3. 4.]
Ceiling: [3. 4. 5.]
Trucated: [2. 3. 4.]


In [34]:
#How to round elements of the NumPy array to the nearest integer?

array = np.array([2.45, 3.65, 4.98])
print(np.rint(array))


[2. 4. 5.]


In [41]:
#Find the round off the values of the given matrix

matrix = np.matrix([[1.45, 2.65, 3.98],[4.45, 5.65, 6.98],[7.45, 38.65, 9.98]])
print(np.round(matrix,0))

[[ 1.  3.  4.]
 [ 4.  6.  7.]
 [ 7. 39. 10.]]


In [43]:
#Determine the positive square-root of an array

array = np.array([1,4,9,16,25])
print(np.sqrt(array))

[1. 2. 3. 4. 5.]


In [44]:
#Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

matrix1 = np.matrix([[1.45, 2.65, 3.98],[4.45, 5.65, 6.98],[7.45, 38.65, 9.98]])
matrix2 = np.matrix([[10.45, 11.65, 12.98],[13.45, 14.65, 15.98],[16.45, 17.65, 18.98]])

print(np.einsum("mk,kn", matrix1, matrix2))

[[116.266  125.962  136.7084]
 [237.316  257.812  280.5284]
 [761.866  829.162  903.7484]]
