In [1]:
import numpy as np

In [9]:
#Replace NumPy array elements that doesn’t satisfy the given condition
array = np.array([1,2,3,4,5,6,7,8,9])
#replace all the odd numbers to 0
array[(array % 2) != 0] = 0
print(array)

[0 2 0 4 0 6 0 8 0]


In [13]:
#Return the indices of elements where the given condition is satisfied

array = np.array([1,2,3,4,5,6,7,8,9])
index = np.where((array % 2) != 0)
print(index[0])

[0 2 4 6 8]


In [60]:
#Replace NaN values with average of columns

array = np.array([[1,2,np.nan],[4,np.nan,6],[7,8,np.nan]])
matrix_mean = np.nanmean(array, axis=0)
index = np.where(np.isnan(array))
array[index] = np.take(matrix_mean, index[1])
print(array)

[[1. 2. 6.]
 [4. 5. 6.]
 [7. 8. 6.]]


In [85]:
#Replace negative value with zero in numpy array

array = np.array([1,-2,3,-4,5,-6,7,-8,9])
array[array < 0] = 0
print(array)

[1 0 3 0 5 0 7 0 9]


In [66]:
#How to get values of an NumPy array at certain index positions?
array = np.array([1,-2,3,-4,5,-6,7,-8,9])

for index in range(len(array)):
    print(f"Valor do array no indice {index}:",array[index])

Valor do array no indice 0: 1
Valor do array no indice 1: -2
Valor do array no indice 2: 3
Valor do array no indice 3: -4
Valor do array no indice 4: 5
Valor do array no indice 5: -6
Valor do array no indice 6: 7
Valor do array no indice 7: -8
Valor do array no indice 8: 9


In [88]:
#Find indices of elements equal to zero in a NumPy array

array = np.array([1,0,3,0,5,0,7,0,9])
index = np.where(array == 0)
print(index[0])

[1 3 5 7]


In [84]:
#How to Remove columns in Numpy array that contains non-numeric values?
array = np.array([[1,2,3],[4,np.nan,6],[7,8,np.nan]])
print(array[:, ~np.isnan(array).any(0)])

[[1.]
 [4.]
 [7.]]


In [86]:
#How to access different rows of a multidimensional NumPy array?
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = array[[0,2]]
print(rows)

[[1 2 3]
 [7 8 9]]


In [94]:
#Get row numbers of NumPy array having element larger than X
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = 3
rows = np.where(array > X)
print(f'As linhas com elementos maiores que {X} são: ',np.unique(rows[0]))

As linhas com elementos maiores que 3 são:  [1 2]


In [96]:
#Get filled the diagonals of NumPy array
array = np.array([[0,0,0],[0,0,0],[0,0,0]])
np.fill_diagonal(array,1)
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [99]:
#Check elements present in the NumPy array
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
tobeChecked = np.array([1,4,7,9,10,11])

for element in tobeChecked:
    print(f'O elemento {element} está presente no array?',element in array)

O elemento está presente no array? True
O elemento está presente no array? True
O elemento está presente no array? True
O elemento está presente no array? True
O elemento está presente no array? False
O elemento está presente no array? False
