In [1]:
import numpy as np

In [2]:
#Find a matrix or vector norm using NumPy

array = np.array([1,2,3])
matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(np.linalg.norm(array))
print(np.linalg.norm(matrix))

3.7416573867739413
16.881943016134134


In [3]:
#Calculate the QR decomposition of a given matrix using NumPy

matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

Q, R = np.linalg.qr(matrix)
print('\nQ:\n', Q)
print('\nR:\n', R)


Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [4]:
#Compute the condition number of a given matrix using NumPy

matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.cond(matrix))

3.813147060626918e+16


In [6]:
#Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
w, v = np.linalg.eig(matrix)

print(w)
print()
print(v)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [11]:
##Calculate the Euclidean distance using NumPy

ponto1 = np.array([1,2,3])
ponto2 = np.array([3,5,3])
print(np.linalg.norm(ponto1 - ponto2))

3.605551275463989
