In [1]:

import numpy as np

In [2]:
#Get the maximum value from given matrix

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.amin(array))

2


In [3]:
#Get the minimum value from given matrix

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print((np.amin(array)))

2


In [4]:
#Find the number of rows and columns of a given matrix using NumPy

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print('Numero de linhas:', array.shape[0])
print('Numero de colunas:', array.shape[1])

Numero de linhas: 4
Numero de colunas: 4


In [5]:
#Select the elements from a given matrix

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print('Elemntro 1,0:', array[1,0])

Elemntro 1,0: 9


In [6]:
#Find the sum of values in a matrix

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.sum(array))

92


In [7]:
#Calculate the sum of the diagonal elements of a NumPy array

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.trace(array))

18


In [8]:
#Adding and Subtracting Matrices in Python

array1 = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
array2 = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])

print(array1 + array2,'\n')
print(array1 - array2)

[[ 4 16 18  8]
 [18  8 18  8]
 [ 8 10 18 14]
 [ 4 18  8  6]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
#Ways to add row/columns in numpy array

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
row = np.array([[1,2,3,4]])

print(np.vstack((array, row)))
print()
print(np.hstack((array, row.T)))

[[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]
 [1 2 3 4]]

[[2 8 9 4 1]
 [9 4 9 4 2]
 [4 5 9 7 3]
 [2 9 4 3 4]]


In [10]:
#Matrix Multiplication in NumPy

array1 = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
array2 =  np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 11]])
print(np.dot(array1,array2))

[[137 160 179]
 [128 154 176]
 [157 182 200]
 [ 96 114 129]]


In [11]:
#Get the eigen values of a matrix

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.linalg.eigvals(array))

[23.43872329+0.j         -5.52816829+0.j          0.0447225 +3.15740354j
  0.0447225 -3.15740354j]


In [12]:
#How to Calculate the determinant of a matrix using NumPy?

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.linalg.det(array))

-1291.9999999999989


In [13]:
#How to inverse a matrix using NumPy

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.linalg.inv(array))

[[-0.14241486  0.13931889 -0.03405573  0.08359133]
 [ 0.00077399 -0.00619195 -0.05959752  0.14628483]
 [ 0.24767802  0.01857585 -0.07120743 -0.18885449]
 [-0.2376161  -0.09907121  0.29643963  0.09055728]]


In [14]:
#How to count the frequency of unique values in NumPy array?

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
print(np.bincount(np.ravel(array)))

[0 0 2 1 5 1 0 1 1 5]


In [15]:
#Multiply matrices of complex numbers using NumPy in Python

array = np.matrix([[2,8,9,4],[9,4,9,4],[4,5,9,7],[2,9,4,3]])
comp = array.astype(complex)
print(np.dot(array,comp))

[[120.+0.j 129.+0.j 187.+0.j 115.+0.j]
 [ 98.+0.j 169.+0.j 214.+0.j 127.+0.j]
 [103.+0.j 160.+0.j 190.+0.j 120.+0.j]
 [107.+0.j  99.+0.j 147.+0.j  81.+0.j]]


In [16]:
#Compute the outer product of two given vectors using NumPy in Python

array1 = np.array([1,2,3])
array2 = np.array([4,4,6])
print(np.outer(array1,array2))

[[ 4  4  6]
 [ 8  8 12]
 [12 12 18]]


In [17]:
#Calculate inner, outer, and cross products of matrices and vectors using NumPy

matrix1 = np.matrix([[2,8,9],[9,4,9],[4,5,9],[2,9,4]])
matrix2 = np.matrix([[1,2,3],[5,6,7],[9,10,11],[13,14,15]])

array1 = np.array([[1,2,3],[1,2,3]])
array2 = np.array([[5,6,7],[1,2,3]])

print('Inner product:')
print('Array:\n', np.inner(array1,array2))
print('Matrix:\n', np.inner(matrix1,matrix2))
print()

print('Outer product:')
print('Array:\n', np.outer(array1,array2))
print('Matrix:\n', np.outer(matrix1,matrix2))
print()

print('Cross product:')
print('Array:\n', np.cross(array1, array2))
print('Matrix:\n', np.cross(matrix1,matrix2))
print()

Inner product:
Array:
 [[38 14]
 [38 14]]
Matrix:
 [[ 45 121 197 273]
 [ 44 132 220 308]
 [ 41 113 185 257]
 [ 32  92 152 212]]

Outer product:
Array:
 [[ 5  6  7  1  2  3]
 [10 12 14  2  4  6]
 [15 18 21  3  6  9]
 [ 5  6  7  1  2  3]
 [10 12 14  2  4  6]
 [15 18 21  3  6  9]]
Matrix:
 [[  2   4   6  10  12  14  18  20  22  26  28  30]
 [  8  16  24  40  48  56  72  80  88 104 112 120]
 [  9  18  27  45  54  63  81  90  99 117 126 135]
 [  9  18  27  45  54  63  81  90  99 117 126 135]
 [  4   8  12  20  24  28  36  40  44  52  56  60]
 [  9  18  27  45  54  63  81  90  99 117 126 135]
 [  4   8  12  20  24  28  36  40  44  52  56  60]
 [  5  10  15  25  30  35  45  50  55  65  70  75]
 [  9  18  27  45  54  63  81  90  99 117 126 135]
 [  2   4   6  10  12  14  18  20  22  26  28  30]
 [  9  18  27  45  54  63  81  90  99 117 126 135]
 [  4   8  12  20  24  28  36  40  44  52  56  60]]

Cross product:
Array:
 [[-4  8 -4]
 [ 0  0  0]]
Matrix:
 [[  6   3  -4]
 [-26 -18  34]
 [-35  37  

In [18]:
#Compute the covariance matrix of two given NumPy arrays

array1 = np.array([[1,2,3],[1,2,3]])
array2 = np.array([[5,6,7],[1,2,3]])
print(np.cov(array1,array2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#Convert covariance matrix to correlation matrix using Python

array1 = np.array([[1,2,],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(np.corrcoef(np.cov(array1,array2)))

[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


c:\Users\tayco\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]


In [20]:
#Compute the Kronecker product of two mulitdimension NumPy arrays

array1 = np.array([[1,2,],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(np.kron(array1,array2))

[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


In [21]:
#Convert the matrix into a list

array = np.array([1,2,3,4,5,6])
print(array.tolist())

[1, 2, 3, 4, 5, 6]
